### PR TITLE
Use ^ notation consistently

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by WyriHaximus** [comment]
Thanks :+1:! Can you include the updated `composer.lock` as well with `composer update nothing` next time? If not I don't mind doing it myself :).

**Comment by GrahamCampbell** [comment]
Sorry, I've just been doing these from github's online editor. I personally wouldn't recommend committing a lock file for projects since it just cases issues like this, and doesn't really have any advantages. The only use for a lock file is locking down the dependencies on an actual application, suitable for deployment into production systems.

**Comment by WyriHaximus** [comment]
Thought you did it that way, no problem I'll just update the lock myself. The reason I'm committing the lock file is so the current locked dependencies, lowest and highest matching composer.json can be tested on travis. It is a safeguard against dependency hell.

**Comment by GrahamCampbell** [comment]
> lowest and highest matching composer.json can be tested on travis. It is a safeguard against dependency hell.

You don't need a lock file to do that though? Take a look at php-cs-fixer's test suite, or indeed symfony's. ;)

**Comment by WyriHaximus** [comment]
Have to commit the lock file when I want to test lowest, current, and highest ;). But anyway your help is much appreciated :+1:

**Pull request merged**
